<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15739" started-at="2018-05-15T20:35:43Z" finished-at="2018-05-15T20:35:58Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15739" started-at="2018-05-15T20:35:43Z" finished-at="2018-05-15T20:35:58Z">
      <class name="settingsTab.TestSettings">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:settingsTab.TestSettings@3c0ecd4b]" name="setUpClass" is-config="true" duration-ms="7129" started-at="2018-05-15T20:35:43Z" finished-at="2018-05-15T20:35:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:settingsTab.TestSettings@3c0ecd4b]" name="setUp" is-config="true" duration-ms="3097" started-at="2018-05-15T20:35:50Z" finished-at="2018-05-15T20:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testSettingsTab()[pri:0, instance:settingsTab.TestSettings@3c0ecd4b]" name="testSettingsTab" duration-ms="85" started-at="2018-05-15T20:35:53Z" finished-at="2018-05-15T20:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSettingsTab -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:settingsTab.TestSettings@3c0ecd4b]" name="setUp" is-config="true" duration-ms="124" started-at="2018-05-15T20:35:53Z" finished-at="2018-05-15T20:35:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testTimelineTrainersPerPage()[pri:1, instance:settingsTab.TestSettings@3c0ecd4b]" name="testTimelineTrainersPerPage" duration-ms="5141" started-at="2018-05-15T20:35:53Z" finished-at="2018-05-15T20:35:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [6]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [6]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at settingsTab.TestSettings.testTimelineTrainersPerPage(TestSettings.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTimelineTrainersPerPage -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:settingsTab.TestSettings@3c0ecd4b]" name="tearDownClass" is-config="true" duration-ms="112" started-at="2018-05-15T20:35:58Z" finished-at="2018-05-15T20:35:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- settingsTab.TestSettings -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
